eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

logstash:
  host: logstash:5000

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

server:
  forward-headers-strategy: framework
  port: 8080
  shutdown: graceful

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route-fx-rate-service
          uri: lb://fx-rate-service
          predicates:
            - Path=/api/fx/**