spring:
  application:
    name: admin-service
  cloud:
    config:
      enabled: true
      fail-fast: true
      label: main
      username: admin
      password: admin
      retry:
        max-attempts: 20
        initial-interval: 10000
        max-interval: 15000
  config:
    import: optional:configserver:http://config-service:8888