eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

logstash:
  host: logstash:5000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  info:
    env:
      enabled: true

server:
  forward-headers-strategy: framework
  port: 8000
  shutdown: graceful

spring:
  application:
    name: admin-service
