spring:
  cloud:
    config:
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: '1.1'
      username: admin
      password: admin
      enabled: true
      label: main
      fail-fast: true
  config:
    import: optional:configserver:http://localhost:8888