global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [
        'localhost:9090'
      ]

  - job_name: 'Xchange App input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [
        'host.docker.internal:8081',
        'host.docker.internal:8761'
      ]
        labels:
          application: "Xchange App"