eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  info:
    env:
      enabled: true

server:
  port: 8000
  shutdown: graceful

spring:
  application:
    name: admin-service