eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: localhost

logstash:
  host: localhost:5000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  info:
    env:
      enabled: true

server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: discovery-service
  boot:
    admin:
      client:
        url: http://localhost:8000