apm:
  application-packages: com.xchangeapp
  enabled: false
  environment: dev
  secret-token: apm
  server-url: http://localhost:8200
  service-name: fx-rate-service

elasticsearch:
  host: localhost
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

exchange-rate-api:
  url: '{cipher}3abd08ff1ca8172fcdaeb570319ad9c93f5c5bc5e8914885fb08b4a69214979e9a6760baa204c6b626673ed9b1e12e290a82479316ed3e80a6317558aeaaef3a2445754cbdc25d1eb6c46b1c405534dd'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: fx-rate-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mvc:
    converters:
      preferred-json-mapper: gson