apm:
  application-packages: com.xchangeapp
  enabled: true
  environment: prod
  secret-token: apm
  server-url: http://apm-server:8200
  service-name: fx-rate-service

elasticsearch:
  host: elasticsearch
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

exchange-rate-api:
  url: 'https://v6.exchangerate-api.com/v6/fd4af74a12bcd97e42211bee'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 0.5
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: fx-rate-service
  mvc:
    converters:
      preferred-json-mapper: gson