eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
      
logging:
  level:
    org.springframework.core.codec.StringDecoder: TRACE

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  info:
    env:
      enabled: true
  tracing:
    sampling:
      endpoint: http://zipkin:9411/api/v2/spans
      probability: 0.5

server:
  forward-headers-strategy: framework
  port: 8080
  shutdown: graceful

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      filter:
        local-response-cache:
          enabled: true
      routes:
        - id: route-fx-rate-service
          uri: lb://fx-rate-service
          predicates:
            - Path=/api/fx/**
          filters:
            - LocalResponseCache=24h,10MB