email:
  subject: Fx Rates for
  from: '{cipher}a54cd464acab79471e2b8a4acbbf2233e9df027a401843d8b95f16789ca010151c9ecd9398b05bb9030f5969ec10d878'
  to: '{cipher}7f2a0c6c51d82634391a654a294b6d6bcb11cc25488a74077e8d334e04f6aa691f02babd2fea17151eda4dbf6cc4c12c'

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

kafka:
  host: kafka:9092
  consumer:
    concurrency: 1

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8100
  shutdown: graceful

spring:
  application:
    name: notification-service
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
        transport:
          protocol: smtp
    host: smtp.office365.com
    username: '{cipher}5d071d75219e32a4d63ffbe212075563a1b346a174055d64d1506da9abfbeb8725b5ae4d74888f9a7dd424a9027f060e'
    password: '{cipher}61071791fdd40c1fab7993e51e057c2dee7f438cd36f3db612bd3734060d6cda'
    port: 587

    
    