server:
  port: 8080
  shutdown: graceful

spring:
  mvc:
    converters:
      preferred-json-mapper: gson

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

exchange-rate-api:
  url: 'https://v6.exchangerate-api.com/v6/fd4af74a12bcd97e42211bee'

elasticsearch:
  host: localhost
  port: 9200

logstash:
  host: localhost:5000

apm:
  enabled: true
  environment: dev
  server-url: http://localhost:8200
  secret-token: apm
  service-name: fx-rate-service
  application-packages: com.xchangeapp
  