apm:
  application-packages: com.xchangeapp
  enabled: true
  environment: dev
  secret-token: apm
  server-url: http://localhost:8200
  service-name: fx-rate-service

elasticsearch:
  host: localhost
  port: 9200

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

exchange-rate-api:
  url: 'https://v6.exchangerate-api.com/v6/fd4af74a12bcd97e42211bee'

logstash:
  host: localhost:5000

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

server:
  forward-headers-strategy: framework
  port: 8081
  shutdown: graceful

spring:
  application:
    name: fx-rate-service
  mvc:
    converters:
      preferred-json-mapper: gson